Add client_secret to OAuth2PKCEAuth instance
client_secret is required for working with OAuth 2.0 in X API. Without it you'll get the following error when calling fetch_token() function:

ValueError: HTTP error! status: 401, body: {'error': 'unauthorized_client', 'error_description': 'Missing valid authorization header'}

Signed-off-by: Abhishek Verma <40134208+w3Abhishek@users.noreply.github.com>